/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugas_uas_smtr2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ibnu Raditya
 */
public class C2dasbor_operator extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(C2dasbor_operator.class.getName());

    /**
     * Creates new form C2dasbor_operator
     */
    public C2dasbor_operator() {
        initComponents();              // ← WAJIB di baris pertama!
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        loadDataPengaduanTerbaru();
        loadRiwayatPengaduan();
        loadStatusPengaduan();
        tbl_rwyt.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tbl_rwyt.getSelectedRow();
            if (row >= 0) {
                String kode = tbl_rwyt.getValueAt(row, 2).toString();
                bukaDetailLaporan(kode);
            }
        }
    });
        cari1.addActionListener(e -> {
            String keyword = jTextField2.getText().trim();
            if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
                loadDataPengaduanTerbaru();
            } else {
                cariPengaduan(keyword, (DefaultTableModel) tbl_trbr.getModel());
            }
        });
        cari2.addActionListener(e -> {
            String keyword = jTextField3.getText().trim();
            if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
                loadRiwayatPengaduan();
            } else {
                cariPengaduan(keyword, (DefaultTableModel) tbl_rwyt.getModel());
            }
        });
        jButton1.addActionListener(e -> {
            int konfirmasi = JOptionPane.showConfirmDialog(null,
                    "Yakin ingin keluar?", "Log Out", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                new C1hal_login_operator().setVisible(true);
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_trbr = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        cari1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_rwyt = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cari2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        cari3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_trbr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pengaduan", "Lokasi ", "Tanggal", "Kode Pengaduan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_trbr);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pengaduan Terbaru");

        jTextField2.setText("Cari Pengaduan");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        cari1.setText("Cari");
        cari1.addActionListener(this::cari1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cari1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_rwyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pengaduan", "Klasifikasi", "Kode Pengaduan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_rwyt);

        jTextField3.setText("Cari Pengaduan");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Riwayat Pengaduan");

        cari2.setText("Cari");
        cari2.addActionListener(this::cari2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cari2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Status Pengaduan");

        jTextField1.setText("Cari Pengaduan");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pengaduan", "Status Pengaduan", "Kode Pengaduan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        cari3.setText("Cari");
        cari3.addActionListener(this::cari3ActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari3)
                .addContainerGap())
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/clerk4.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Nama Operator");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Shift");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/logout.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Log Out");

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SILANDAK");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sistem Layanan dan Pengaduan Damkar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(634, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(228, 228, 228)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField2.getText().trim();
        if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
            loadDataPengaduanTerbaru();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) tbl_trbr.getModel());
        }

    }//GEN-LAST:event_cari1ActionPerformed

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField3.getText().trim();
        if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
            loadRiwayatPengaduan();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) tbl_rwyt.getModel());
        }

    }//GEN-LAST:event_cari2ActionPerformed

    private void cari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari3ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField1.getText().trim();
        if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
            loadStatusPengaduan();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) jTable6.getModel());
        }
    }//GEN-LAST:event_cari3ActionPerformed

    private void loadDataPengaduanTerbaru() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Pengaduan", "Lokasi", "Tanggal", "Kode Pengaduan"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3;
            }
        };

        try {
            Connection conn = dbconnectionsistem.getKoneksi();
            String sql = "SELECT deskripsi, alamat_kejadian, waktu_kejadian, kode_pengaduan "
                    + "FROM form_pengaduan ORDER BY waktu_kejadian DESC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("deskripsi"),
                    rs.getString("alamat_kejadian"),
                    rs.getTimestamp("waktu_kejadian").toString(),
                    rs.getString("kode_pengaduan")
                });
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }

        tbl_trbr.setModel(model);
        setupTombolDetail();
    }

    // Hapus kolom "Detail" jika masih ada (kolom index 5)
    private void setupTombolDetail() {
        tbl_trbr.getColumnModel().getColumn(3).setCellRenderer(new KodeWithButtonRenderer());
        tbl_trbr.getColumnModel().getColumn(3).setCellEditor(new KodeWithButtonEditor());
        tbl_trbr.getColumnModel().getColumn(3).setPreferredWidth(220);
        tbl_trbr.getColumnModel().getColumn(3).setMinWidth(200);
        tbl_trbr.setRowHeight(28);
    }

    private void bukaDetailPengaduan(int row) {
    String kodePengaduan = tbl_trbr.getValueAt(row, 3).toString();

    try {
        Connection conn = dbconnectionsistem.getKoneksi();
        String sql = "SELECT * FROM form_pengaduan WHERE kode_pengaduan = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, kodePengaduan);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            detailpengaduanterbaruOperator detail = new detailpengaduanterbaruOperator(
                rs.getString("kode_pengaduan"),
                rs.getString("deskripsi"),
                rs.getString("alamat_kejadian"),
                rs.getTimestamp("waktu_kejadian").toString(),
                jLabel6.getText(),  // ← nama operator
                jLabel7.getText()   // ← shift
            );
            detail.setVisible(true);
        }
        rs.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal membuka detail: " + e.getMessage());
    }
}

    // ===== Inner class: tombol icon search =====
    class KodeWithButtonRenderer extends javax.swing.JPanel implements javax.swing.table.TableCellRenderer {

        private final javax.swing.JLabel lblKode = new javax.swing.JLabel();
        private final javax.swing.JButton btnSearch = new javax.swing.JButton();

        public KodeWithButtonRenderer() {
            setLayout(new java.awt.BorderLayout());
            java.awt.Image img = new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/search.png"))
                    .getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH);
            btnSearch.setIcon(new javax.swing.ImageIcon(img));
            btnSearch.setPreferredSize(new java.awt.Dimension(24, 24));
            btnSearch.setBorderPainted(false);
            btnSearch.setFocusPainted(false);
            btnSearch.setContentAreaFilled(false);
            add(lblKode, java.awt.BorderLayout.CENTER);
            add(btnSearch, java.awt.BorderLayout.EAST);
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            lblKode.setText(value != null ? value.toString() : "");
            setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
            lblKode.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
            setOpaque(true);
            return this;
        }
    }

    class KodeWithButtonEditor extends javax.swing.DefaultCellEditor {

        private final javax.swing.JPanel panel = new javax.swing.JPanel();
        private final javax.swing.JLabel lblKode = new javax.swing.JLabel();
        private final javax.swing.JButton btnSearch = new javax.swing.JButton();
        private int currentRow;

        public KodeWithButtonEditor() {
            super(new javax.swing.JCheckBox());
            panel.setLayout(new java.awt.BorderLayout());
            java.awt.Image img = new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/search.png"))
                    .getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH);
            btnSearch.setIcon(new javax.swing.ImageIcon(img));
            btnSearch.setPreferredSize(new java.awt.Dimension(24, 24));
            btnSearch.setBorderPainted(false);
            btnSearch.setFocusPainted(false);
            btnSearch.setContentAreaFilled(false);
            panel.add(lblKode, java.awt.BorderLayout.CENTER);
            panel.add(btnSearch, java.awt.BorderLayout.EAST);

            btnSearch.addActionListener(e -> {
                fireEditingStopped();
                bukaDetailPengaduan(currentRow);
            });
        }

        @Override
        public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value,
                boolean isSelected, int row, int column) {
            lblKode.setText(value != null ? value.toString() : "");
            this.currentRow = row;
            return panel;
        }

        @Override
        public Object getCellEditorValue() {
            return lblKode.getText();
        }
    }

    private void loadRiwayatPengaduan() {
    DefaultTableModel model = (DefaultTableModel) tbl_rwyt.getModel();
    model.setRowCount(0);
    Connection con = dbconnectionsistem.getKoneksi();
    if (con == null) return;

    String sql = "SELECT fp.deskripsi, fp.klasifikasi, fp.kode_pengaduan " +
                 "FROM form_pengaduan fp " +
                 "INNER JOIN laporan_penanganan lp ON fp.id_form_pengaduan = lp.id_form_pengaduan " +
                 "ORDER BY lp.created_at DESC";
    try {
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            String klas = rs.getString("klasifikasi").equals("emergency") ? "E" : "N.e";
            model.addRow(new Object[]{
                rs.getString("deskripsi"),
                klas,
                rs.getString("kode_pengaduan")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error load riwayat: " + e.getMessage());
    }
}

    private void loadStatusPengaduan() {
        DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
        model.setRowCount(0);
        Connection con = dbconnectionsistem.getKoneksi();
        if (con == null) {
            return;
        }
        String sql = "SELECT deskripsi, status, kode_pengaduan FROM form_pengaduan ORDER BY created_at DESC";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String status = switch (rs.getString("status")) {
                    case "masuk_sistem" ->
                        "Masuk Sistem";
                    case "diproses" ->
                        "Diproses";
                    case "ditangani" ->
                        "Ditangani";
                    case "selesai" ->
                        "Selesai";
                    case "ditolak" ->
                        "Ditolak";
                    default ->
                        rs.getString("status");
                };
                model.addRow(new Object[]{
                    rs.getString("deskripsi"),
                    status,
                    rs.getString("kode_pengaduan")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error load status: " + e.getMessage());
        }
    }

    private void cariPengaduan(String kode, DefaultTableModel model) {
        model.setRowCount(0);
        Connection con = dbconnectionsistem.getKoneksi();
        if (con == null) {
            return;
        }

        String sql = "SELECT deskripsi, alamat_kejadian, waktu_kejadian, klasifikasi, kode_pengaduan, status "
                + "FROM form_pengaduan "
                + "WHERE kode_pengaduan = ? "
                + "ORDER BY created_at DESC";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, kode);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String klas = rs.getString("klasifikasi").equals("emergency") ? "E" : "N.e";
                String status = switch (rs.getString("status")) {
                    case "masuk_sistem" ->
                        "Masuk Sistem";
                    case "diproses" ->
                        "Diproses";
                    case "ditangani" ->
                        "Ditangani";
                    case "selesai" ->
                        "Selesai";
                    case "ditolak" ->
                        "Ditolak";
                    default ->
                        rs.getString("status");
                };
                if (model.getColumnCount() == 4) {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        rs.getString("alamat_kejadian"),
                        rs.getString("waktu_kejadian"),
                        rs.getString("kode_pengaduan")
                    });
                } else if (model.getColumnCount() == 3 && model.getColumnName(1).equals("Klasifikasi")) {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        klas,
                        rs.getString("kode_pengaduan")
                    });
                } else {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        status,
                        rs.getString("kode_pengaduan")
                    });
                }
            }
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Kode pengaduan tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField2.getText().trim();
        if (keyword.isEmpty()) {
            loadDataPengaduanTerbaru();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) tbl_trbr.getModel());
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField3.getText().trim();
        if (keyword.isEmpty()) {
            loadRiwayatPengaduan();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) tbl_rwyt.getModel());
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField1.getText().trim();
        if (keyword.isEmpty()) {
            loadStatusPengaduan();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) jTable6.getModel());
        }
    }

    public void setInfoOperator(String nama, String shift) {
        jLabel6.setText(nama);
        jLabel7.setText("Shift: " + shift);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);

        }
        /**
         * @param args the command line arguments
         */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new C2dasbor_operator().setVisible(true));
    }
    private void bukaDetailLaporan(String kodePengaduan) {
  
    Connection con = dbconnectionsistem.getKoneksi();
    if (con == null) return;

    String sql = "SELECT fp.kode_pengaduan, fp.deskripsi, fp.alamat_kejadian, " +
                 "fp.waktu_kejadian, fp.latitude, fp.longitude, " +
                 "lp.deskripsi_penanganan, lp.tanggal_laporan, " +
                 "i.nama_instansi, i.shift " +
                 "FROM form_pengaduan fp " +
                 "INNER JOIN laporan_penanganan lp ON fp.id_form_pengaduan = lp.id_form_pengaduan " +
                 "LEFT JOIN instansi i ON lp.id_instansi = i.id_instansi " +
                 "WHERE fp.kode_pengaduan = ?";
    try {
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, kodePengaduan);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            double lat = rs.getDouble("latitude");
            double lng = rs.getDouble("longitude");
            String lokasiMaps = lat + "," + lng;

            DetailLaporanHasilPenangananOperator detail = new DetailLaporanHasilPenangananOperator(
                rs.getString("kode_pengaduan"),
                rs.getString("deskripsi_penanganan"),
                rs.getString("alamat_kejadian"),
                rs.getString("tanggal_laporan"),
                rs.getString("nama_instansi"),
                rs.getString("shift"),
                lokasiMaps
            );
            detail.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Laporan belum tersedia untuk pengaduan ini");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

}

    public void hapusBarisDariTabel(String kodePengaduan) {
        DefaultTableModel model = (DefaultTableModel) tbl_trbr.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 3) != null
                    && model.getValueAt(i, 3).toString().equals(kodePengaduan)) {
                model.removeRow(i);
                break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari2;
    private javax.swing.JButton cari3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tbl_rwyt;
    private javax.swing.JTable tbl_trbr;
    // End of variables declaration//GEN-END:variables

}
