/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugas_uas_smtr2;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI Modern
 */
public class DasborInstansi1 extends javax.swing.JFrame {

    private int idInstansiDinamis;
    private String namaInstansiData = "";  // ✅ tambah ini
    private String shiftInstansiData = "";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DasborInstansi1.class.getName());

    /**
     * Creates new form DasborInstansi1
     */
    public DasborInstansi1(int idInstansiDinamis) {
        initComponents();
        this.idInstansiDinamis = idInstansiDinamis;
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        loadPengaduanTerbaru();
        loadRiwayatPengaduan();
        
        cari1.addActionListener(e -> {
            String keyword = jTextField2.getText().trim();
            if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
                loadPengaduanTerbaru();
            } else {
                cariPengaduan(keyword, (DefaultTableModel) tbl_pengaduan.getModel());
            }
        });
        
        jButton1.addActionListener(e -> {
            int konfirmasi = JOptionPane.showConfirmDialog(null,
                    "Yakin ingin keluar?", "Log Out", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                new logininstansi().setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengaduan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        cari1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cari2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_pengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pengaduan", "Lokasi ", "Tanggal", "Klasifikasi", "Kode Pengaduan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_pengaduan);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pengaduan Terbaru");

        jTextField2.setText("Cari Pengaduan");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        cari1.setText("Cari");
        cari1.addActionListener(this::cari1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 660, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cari1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pengaduan", "Status", "Kode Pengaduan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTextField3.setText("Cari Pengaduan");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Riwayat Pengaduan");

        cari2.setText("Cari");
        cari2.addActionListener(this::cari2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cari2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/clerk4.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Nama ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Shift");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/logout.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Log Out");

        jPanel3.setBackground(new java.awt.Color(237, 28, 36));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SILANDAK");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sistem Layanan dan Pengaduan Damkar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(632, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(603, 603, 603))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(156, 156, 156)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(261, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        // TODO add your handling code here:
        cari1.addActionListener(this::jButton3ActionPerformed);
    }//GEN-LAST:event_cari1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
         String keyword = jTextField3.getText().trim();
    if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
        loadRiwayatPengaduan();
    } else {
        cariRiwayat(keyword);
    }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField3.getText().trim();
    if (keyword.isEmpty() || keyword.equals("Cari Pengaduan")) {
        loadRiwayatPengaduan();
    } else {
        cariRiwayat(keyword);
    }
    }//GEN-LAST:event_cari2ActionPerformed
    public void tambahPengaduanKeInstansi(String pengaduan, String lokasi, String tanggal, String klasifikasi, String kodePengaduan) {

        DefaultTableModel model = (DefaultTableModel) tbl_pengaduan.getModel();

        // Cek apakah kode pengaduan sudah ada di tabel agar tidak duplikat
        if (model.getColumnCount() != 5) {
            loadPengaduanTerbaru(); // inisialisasi model kosong dulu
            model = (DefaultTableModel) tbl_pengaduan.getModel();
        }

        // Cek duplikat
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 4) != null
                    && model.getValueAt(i, 4).toString().equals(kodePengaduan)) {
                return;
            }
        }

        model.addRow(new Object[]{
            pengaduan,
            lokasi,
            tanggal,
            klasifikasi,
            kodePengaduan
        });

        // Pasang renderer dan editor ulang supaya tombol icon search tetap muncul
        setupTombolDetail();
    }

    private void setupTombolDetail() {
        tbl_pengaduan.getColumnModel().getColumn(4).setCellRenderer(new DasborInstansi1.KodeWithButtonRenderer());
        tbl_pengaduan.getColumnModel().getColumn(4).setCellEditor(new DasborInstansi1.KodeWithButtonEditor());
        tbl_pengaduan.getColumnModel().getColumn(4).setPreferredWidth(220);
        tbl_pengaduan.getColumnModel().getColumn(4).setMinWidth(200);
        tbl_pengaduan.setRowHeight(28);
    }

    private void bukaDetailPengaduan(int row) {
        String kodePengaduan = tbl_pengaduan.getValueAt(row, 4).toString(); // ← index 4

        try (Connection conn = java.sql.DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:3306/silandak", "root", "")) {
            String sql = "SELECT * FROM form_pengaduan WHERE kode_pengaduan = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kodePengaduan);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                DetailPengaduanTerbaruInstansi detail = new DetailPengaduanTerbaruInstansi(
                        rs.getString("kode_pengaduan"),
                        rs.getString("deskripsi"),
                        rs.getString("alamat_kejadian"),
                        rs.getTimestamp("waktu_kejadian").toString(),
                        this.idInstansiDinamis,
                        this.namaInstansiData, // ✅ teruskan
                        this.shiftInstansiData
                );
                detail.setVisible(true);
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuka detail: " + e.getMessage());
        }
    }

    class KodeWithButtonRenderer extends javax.swing.JPanel implements javax.swing.table.TableCellRenderer {

        private final javax.swing.JLabel lblKode = new javax.swing.JLabel();
        private final javax.swing.JButton btnSearch = new javax.swing.JButton();

        public KodeWithButtonRenderer() {
            setLayout(new java.awt.BorderLayout());
            java.awt.Image img = new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/search.png"))
                    .getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH);
            btnSearch.setIcon(new javax.swing.ImageIcon(img));
            btnSearch.setPreferredSize(new java.awt.Dimension(24, 24));
            btnSearch.setBorderPainted(false);
            btnSearch.setFocusPainted(false);
            btnSearch.setContentAreaFilled(false);
            add(lblKode, java.awt.BorderLayout.CENTER);
            add(btnSearch, java.awt.BorderLayout.EAST);
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            lblKode.setText(value != null ? value.toString() : "");
            setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
            lblKode.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
            setOpaque(true);
            return this;
        }
    }

    class KodeWithButtonEditor extends javax.swing.DefaultCellEditor {

        private final javax.swing.JPanel panel = new javax.swing.JPanel();
        private final javax.swing.JLabel lblKode = new javax.swing.JLabel();
        private final javax.swing.JButton btnSearch = new javax.swing.JButton();
        private int currentRow;

        public KodeWithButtonEditor() {
            super(new javax.swing.JCheckBox());
            panel.setLayout(new java.awt.BorderLayout());
            java.awt.Image img = new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/tugas_uas_smtr2/images/search.png"))
                    .getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH);
            btnSearch.setIcon(new javax.swing.ImageIcon(img));
            btnSearch.setPreferredSize(new java.awt.Dimension(24, 24));
            btnSearch.setBorderPainted(false);
            btnSearch.setFocusPainted(false);
            btnSearch.setContentAreaFilled(false);
            panel.add(lblKode, java.awt.BorderLayout.CENTER);
            panel.add(btnSearch, java.awt.BorderLayout.EAST);

            btnSearch.addActionListener(e -> {
                fireEditingStopped();
                bukaDetailPengaduan(currentRow);
            });
        }

        @Override
        public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value,
                boolean isSelected, int row, int column) {
            lblKode.setText(value != null ? value.toString() : "");
            this.currentRow = row;
            return panel;
        }

        @Override
        public Object getCellEditorValue() {
            return lblKode.getText();
        }
    }

    private void loadPengaduanTerbaru() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Pengaduan", "Lokasi", "Tanggal", "Klasifikasi", "Kode Pengaduan"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4;
            }
        };

        // Load dari DB: hanya yang klasifikasi = 'emergency'
        try (Connection conn = java.sql.DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:3306/silandak", "root", "")) {
            String sql = "SELECT deskripsi, alamat_kejadian, waktu_kejadian, klasifikasi, kode_pengaduan "
                    + "FROM form_pengaduan WHERE klasifikasi IN ('emergency', 'non_emergency') ORDER BY waktu_kejadian DESC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String statusKlasifikasi = rs.getString("klasifikasi");
                String labelKlasifikasi = "emergency".equalsIgnoreCase(statusKlasifikasi) ? "E" : "N.e";
                model.addRow(new Object[]{
                    rs.getString("deskripsi"),
                    rs.getString("alamat_kejadian"),
                    rs.getTimestamp("waktu_kejadian").toString(),
                    labelKlasifikasi,
                    rs.getString("kode_pengaduan")
                });
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }

        tbl_pengaduan.setModel(model);
        setupTombolDetail();
    }

   private void loadRiwayatPengaduan() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"Pengaduan", "Status", "Kode Pengaduan"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    try (Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://127.0.0.1:3306/silandak", "root", "")) {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT deskripsi, status, kode_pengaduan FROM form_pengaduan ORDER BY created_at DESC");
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            String status = switch (rs.getString("status")) {
                case "masuk_sistem" -> "Masuk Sistem";
                case "diproses"     -> "Diproses";
                case "ditangani"    -> "Ditangani";
                case "selesai"      -> "Selesai";
                case "ditolak"      -> "Ditolak";
                default             -> rs.getString("status");
            };
            model.addRow(new Object[]{
                rs.getString("deskripsi"),
                status,
                rs.getString("kode_pengaduan")
            });
        }
        rs.close();
        ps.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error load riwayat: " + e.getMessage());
    }

    jTable2.setModel(model);
}

    

    private void cariPengaduan(String kode, DefaultTableModel model) {
        model.setRowCount(0);
        try (Connection conn = java.sql.DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:3306/silandak", "root", "")) {
            String sql = "SELECT deskripsi, alamat_kejadian, waktu_kejadian, klasifikasi, kode_pengaduan, status "
                    + "FROM form_pengaduan WHERE kode_pengaduan = ? ORDER BY created_at DESC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kode);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String klas = rs.getString("klasifikasi").equals("emergency") ? "E" : "N.e";
                String status = switch (rs.getString("status")) {
                    case "masuk_sistem" ->
                        "Masuk Sistem";
                    case "diproses" ->
                        "Diproses";
                    case "ditangani" ->
                        "Ditangani";
                    case "selesai" ->
                        "Selesai";
                    case "ditolak" ->
                        "Ditolak";
                    default ->
                        rs.getString("status");
                };
                if (model.getColumnCount() == 5) {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        rs.getString("alamat_kejadian"),
                        rs.getString("waktu_kejadian"),
                        klas,
                        rs.getString("kode_pengaduan")
                    });
                } else if (model.getColumnCount() == 3 && model.getColumnName(1).equals("Klasifikasi")) {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        klas,
                        rs.getString("kode_pengaduan")
                    });
                } else {
                    model.addRow(new Object[]{
                        rs.getString("deskripsi"),
                        status,
                        rs.getString("kode_pengaduan")
                    });
                }
            }
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Kode pengaduan tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
    private void cariRiwayat(String keyword) {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"Pengaduan", "Status", "Kode Pengaduan"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    try (Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://127.0.0.1:3306/silandak", "root", "")) {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT deskripsi, status, kode_pengaduan FROM form_pengaduan "
          + "WHERE kode_pengaduan LIKE ? OR deskripsi LIKE ? "
          + "ORDER BY created_at DESC");
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            String status = switch (rs.getString("status")) {
                case "masuk_sistem" -> "Masuk Sistem";
                case "diproses"     -> "Diproses";
                case "ditangani"    -> "Ditangani";
                case "selesai"      -> "Selesai";
                case "ditolak"      -> "Ditolak";
                default             -> rs.getString("status");
            };
            model.addRow(new Object[]{
                rs.getString("deskripsi"),
                status,
                rs.getString("kode_pengaduan")
            });
        }
        rs.close();
        ps.close();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan: " + keyword);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error cari riwayat: " + e.getMessage());
    }

    jTable2.setModel(model);
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField2.getText().trim();
        if (keyword.isEmpty()) {
            loadPengaduanTerbaru();
        } else {
            cariPengaduan(keyword, (DefaultTableModel) tbl_pengaduan.getModel());
        }
    }

    public void setInfoInstansi(String nama, String shift) {
        this.namaInstansiData = nama;   // ✅ simpan ke field
        this.shiftInstansiData = shift;
        jLabel6.setText(nama);
        jLabel7.setText("Shift: " + shift);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);

        }

        /**
         * @param args the command line arguments
         */
        java.awt.EventQueue.invokeLater(
                () -> new DasborInstansi1(0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tbl_pengaduan;
    // End of variables declaration//GEN-END:variables

    private void jButton4ActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
