/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugas_uas_smtr2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI Modern
 */
public class isilaporanhasilpenangananInstansi extends javax.swing.JFrame {
    private double currentLat;  
    private double currentLng;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(isilaporanhasilpenangananInstansi.class.getName());

    /**
     * Creates new form laporandetaillaporanhasilpenanganan
     */
    public isilaporanhasilpenangananInstansi() {
        initComponents();
        
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Gambar (*.png, *.jpg)", "png", "jpg", "jpeg"));
        
    }
        private String kodePengaduanData;
        private String deskripsiData;
        private String alamatData;
        private String waktuData;
        

// TAMBAHKAN INI: Untuk menampung path file pilihan JFileChooser sebelum dikirim
        private String pathFileTerpilih = null;
       
        private int idInstansiDinamis;

         public isilaporanhasilpenangananInstansi(String kodePengaduan, String deskripsi, String alamat,
                       String waktuKejadian, int idInstansi
                       ) {
        initComponents();
        field_kd.setText(kodePengaduan);
        
        area_alamat.setText(alamat);
        field_tgl.setText(waktuKejadian);
        
        this.kodePengaduanData = kodePengaduan;
        this.deskripsiData = deskripsi;
        this.alamatData = alamat;
        this.waktuData = waktuKejadian;
        
        this.idInstansiDinamis = idInstansi;
        btn_lihat_lokasi.setEnabled(false);
        javax.swing.SwingUtilities.invokeLater(() -> loadFotoAndMaps(kodePengaduan));
    }
        private void loadFotoAndMaps(String kodePengaduan) {
    System.out.println("DEBUG - kodePengaduan masuk: " + kodePengaduan);

    try {
        // Buat koneksi baru langsung, jangan pakai try-with-resources
        java.sql.Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/silandak", "root", ""
        );

        String sql = "SELECT latitude, longitude FROM form_pengaduan WHERE kode_pengaduan = ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, kodePengaduan);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            double lat = rs.getDouble("latitude");
            double lng = rs.getDouble("longitude");
           

            currentLat = lat;
            currentLng = lng;
            Util.tampilkanMapsPreview(lbl_maps, currentLat, currentLng);
            btn_lihat_lokasi.setEnabled(true);
        } else {
            
            lbl_maps.setText("Data tidak ditemukan");
        }

        rs.close();
        ps.close();
        conn.close(); // tutup manual di akhir

    } catch (Exception e) {
        System.out.println("DEBUG - Exception: " + e.getMessage());
        e.printStackTrace();
        lbl_maps.setText("Gagal memuat peta");
        btn_lihat_lokasi.setEnabled(false);
    }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_detail = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_kirim = new javax.swing.JButton();
        btn_lihat_lokasi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_alamat = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        field_tgl = new javax.swing.JTextField();
        field_kd = new javax.swing.JTextField();
        lbl_maps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("SILANDAK");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Sistem Layanan Dan Pengaduan Damkar");

        jButton1.setText("< Kembali");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Deskripsi Penanganan");

        area_detail.setColumns(20);
        area_detail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        area_detail.setLineWrap(true);
        area_detail.setRows(5);
        area_detail.setWrapStyleWord(true);
        jScrollPane1.setViewportView(area_detail);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Alamat");

        btn_kirim.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_kirim.setText("KIRIM");
        btn_kirim.addActionListener(this::btn_kirimActionPerformed);

        btn_lihat_lokasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_lihat_lokasi.setText("Lihat Lokasi");
        btn_lihat_lokasi.addActionListener(this::btn_lihat_lokasiActionPerformed);

        area_alamat.setColumns(20);
        area_alamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        area_alamat.setLineWrap(true);
        area_alamat.setRows(5);
        area_alamat.setWrapStyleWord(true);
        jScrollPane3.setViewportView(area_alamat);

        jFileChooser1.addActionListener(this::jFileChooser1ActionPerformed);

        field_tgl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        field_kd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbl_maps.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addComponent(btn_lihat_lokasi)
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(259, 259, 259))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(695, 695, 695)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_maps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_kd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(field_kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(69, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_kirim)
                                .addContainerGap(201, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_maps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btn_lihat_lokasi)
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(field_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        // TODO add your handling code here:
        
    // 1. Ambil data teks dari GUI
    String kodePengaduan = field_kd.getText();          // Contoh: "EMR-0001" atau "NEM-0001"
    String tglLaporan = field_tgl.getText();            
    String deskripsiPenanganan = area_detail.getText(); 
    String alamat = area_alamat.getText();

    // Sementara di-hardcode 1 karena belum ada Session Login
    int idInstansi = this.idInstansiDinamis; 
    int idOperatorLogedIn = 1; 

    // 2. Ambil file dari JFileChooser
    java.io.File fileGambar = jFileChooser1.getSelectedFile(); 
    if (fileGambar == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Silakan pilih file gambar PNG terlebih dahulu!");
        return; 
    }
       // Sudah dibahas sebelumnya — tambahkan prefix sebelum simpan ke DB
    String base64Gambar = "";
try {
    byte[] fileBytes = java.nio.file.Files.readAllBytes(fileGambar.toPath());
    String base64Raw = java.util.Base64.getEncoder().encodeToString(fileBytes);
    
    // Deteksi MIME type dari ekstensi file
    String namaFile = fileGambar.getName().toLowerCase();
    String mimeType;
    if (namaFile.endsWith(".png")) {
        mimeType = "image/png";
    } else if (namaFile.endsWith(".jpg") || namaFile.endsWith(".jpeg")) {
        mimeType = "image/jpeg";
    } else {
        mimeType = "image/png"; // default
    }
    
    // Gabungkan prefix + Base64
    base64Gambar = "data:" + mimeType + ";base64," + base64Raw;
    
} catch (java.io.IOException ex) {
    ex.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Gagal membaca file gambar: " + ex.getMessage(), "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
    String url = "jdbc:mysql://localhost:3306/silandak";
    String kodeLaporanOtomatis = "";
    
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");
        
        // =======================================================================
        // A. CEK KLASIFIKASI PENGADUAN & HITUNG ID TERAKHIR
        // =======================================================================
        // Query untuk mengambil klasifikasi dan menghitung jumlah laporan yang ada
        String sqlCekKlasifikasi = "SELECT klasifikasi FROM form_pengaduan WHERE kode_pengaduan = ?";
        java.sql.PreparedStatement psCekKla = conn.prepareStatement(sqlCekKlasifikasi);
        psCekKla.setString(1, kodePengaduan);
        java.sql.ResultSet rsCekKla = psCekKla.executeQuery();
        
        String jenisKlasifikasi = "emergency"; // Default cadangan
        if (rsCekKla.next()) {
            jenisKlasifikasi = rsCekKla.getString("klasifikasi"); // mengambil 'emergency' atau 'non_emergency'
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Kode Pengaduan tidak ditemukan di database!");
            return;
        }
        rsCekKla.close();
        psCekKla.close();

        // Cari ID Terakhir untuk nomor urut kode laporan baru
        
        // =======================================================================

        
        // 3. JALANKAN QUERY INSERT
        String sqlInsert = "INSERT INTO laporan_penanganan "
                   + "(kode_laporan, id_form_pengaduan, id_instansi, id_operator, deskripsi_penanganan, alamat, tanggal_laporan, foto_media) "
                   + "VALUES (?, (SELECT id_form_pengaduan FROM form_pengaduan WHERE kode_pengaduan = ?), ?, ?, ?, ?, ?, ?)";
        
        java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
        
        psInsert.setString(1, kodeLaporanOtomatis); 
        psInsert.setString(2, kodePengaduan);       
        psInsert.setInt(3, idInstansiDinamis);      
        psInsert.setInt(4, idOperatorLogedIn);      
        psInsert.setString(5, deskripsiPenanganan); 
        psInsert.setString(6, alamat);              
        psInsert.setString(7, tglLaporan);
        psInsert.setString(8, base64Gambar);
        
        
        
        int rows = psInsert.executeUpdate();
        if (rows > 0) {
            String sqlUpdate = "UPDATE form_pengaduan SET status = 'selesai' WHERE kode_pengaduan = ?";
            java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setString(1, kodePengaduan);
            psUpdate.executeUpdate();
            psUpdate.close();
            javax.swing.JOptionPane.showMessageDialog(null, 
                "Laporan berhasil dikirim!\nKode Laporan Baru: " + kodeLaporanOtomatis);
            area_detail.setText("");
             area_alamat.setText("");
            jFileChooser1.setSelectedFile(null);
            this.dispose(); // tutup form setelah sukses
        }
        
        psInsert.close();
        
        conn.close();
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }

    
   
        
       
    

    

   

    }//GEN-LAST:event_btn_kirimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DetailPengaduanTerbaruInstansi keluar = new DetailPengaduanTerbaruInstansi();
        keluar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_lihat_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihat_lokasiActionPerformed
        btn_lihat_lokasi.addActionListener(e -> {
        Util.bukaMapsDiBrowser(
        String.format(java.util.Locale.US,
            "https://www.google.com/maps?q=%f,%f", 
            currentLat, currentLng)
    );
});        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lihat_lokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new isilaporanhasilpenangananInstansi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_alamat;
    private javax.swing.JTextArea area_detail;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_lihat_lokasi;
    private javax.swing.JTextField field_kd;
    private javax.swing.JTextField field_tgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_maps;
    // End of variables declaration//GEN-END:variables
}
