/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugas_uas_smtr2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI Modern
 */
public class isilaporanhasilpenangananInstansi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(isilaporanhasilpenangananInstansi.class.getName());

    /**
     * Creates new form laporandetaillaporanhasilpenanganan
     */
    public isilaporanhasilpenangananInstansi() {
        initComponents();
        
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Gambar (*.png, *.jpg)", "png", "jpg", "jpeg"));
        
    }
        private String kodePengaduanData;
        private String deskripsiData;
        private String alamatData;
        private String waktuData;
        

// TAMBAHKAN INI: Untuk menampung path file pilihan JFileChooser sebelum dikirim
        private String pathFileTerpilih = null;

         public isilaporanhasilpenangananInstansi(String kodePengaduan, String deskripsi, String alamat,
                       String waktuKejadian
                       ) {
        initComponents();
        field_kd.setText(kodePengaduan);
        
        area_alamat.setText(alamat);
        field_tgl.setText(waktuKejadian);
        
        this.kodePengaduanData = kodePengaduan;
        this.deskripsiData = deskripsi;
        this.alamatData = alamat;
        this.waktuData = waktuKejadian;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_detail = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_kirim = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_alamat = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        field_tgl = new javax.swing.JTextField();
        field_kd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("SILANDAK");

        jLabel5.setText("Sistem Layanan Dan Pengaduan Damkar");

        jButton1.setText("< Kembali");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Deskripsi Penanganan");

        area_detail.setColumns(20);
        area_detail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        area_detail.setLineWrap(true);
        area_detail.setRows(5);
        area_detail.setWrapStyleWord(true);
        jScrollPane1.setViewportView(area_detail);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Alamat");

        btn_kirim.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_kirim.setText("KIRIM");
        btn_kirim.addActionListener(this::btn_kirimActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Lihat Lokasi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        area_alamat.setColumns(20);
        area_alamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        area_alamat.setLineWrap(true);
        area_alamat.setRows(5);
        area_alamat.setWrapStyleWord(true);
        jScrollPane3.setViewportView(area_alamat);

        jFileChooser1.addActionListener(this::jFileChooser1ActionPerformed);

        field_tgl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        field_kd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel4))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 889, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(334, 334, 334)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(field_kd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(field_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(field_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(btn_kirim))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1)))
                        .addGap(38, 38, 38)
                        .addComponent(field_kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(427, 427, 427)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        // TODO add your handling code here:
        
    // 1. Ambil data teks dari GUI
    String kodePengaduan = field_kd.getText();          // Contoh: "EMR-0001" atau "NEM-0001"
    String tglLaporan = field_tgl.getText();            
    String deskripsiPenanganan = area_detail.getText(); 
    String alamat = area_alamat.getText();

    // Sementara di-hardcode 1 karena belum ada Session Login
    int idInstansiLogedIn = 1; 
    int idOperatorLogedIn = 1; 

    // 2. Ambil file dari JFileChooser
    java.io.File fileGambar = jFileChooser1.getSelectedFile(); 
    if (fileGambar == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Silakan pilih file gambar PNG terlebih dahulu!");
        return; 
    }

    String url = "jdbc:mysql://localhost:3306/silandak";
    String kodeLaporanOtomatis = "";

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");
        
        // =======================================================================
        // A. CEK KLASIFIKASI PENGADUAN & HITUNG ID TERAKHIR
        // =======================================================================
        // Query untuk mengambil klasifikasi dan menghitung jumlah laporan yang ada
        String sqlCekKlasifikasi = "SELECT klasifikasi FROM form_pengaduan WHERE kode_pengaduan = ?";
        java.sql.PreparedStatement psCekKla = conn.prepareStatement(sqlCekKlasifikasi);
        psCekKla.setString(1, kodePengaduan);
        java.sql.ResultSet rsCekKla = psCekKla.executeQuery();
        
        String jenisKlasifikasi = "emergency"; // Default cadangan
        if (rsCekKla.next()) {
            jenisKlasifikasi = rsCekKla.getString("klasifikasi"); // mengambil 'emergency' atau 'non_emergency'
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Kode Pengaduan tidak ditemukan di database!");
            return;
        }
        rsCekKla.close();
        psCekKla.close();

        // Cari ID Terakhir untuk nomor urut kode laporan baru
        String sqlCekId = "SELECT MAX(id_laporan) AS max_id FROM laporan_penanganan";
        java.sql.PreparedStatement psCekId = conn.prepareStatement(sqlCekId);
        java.sql.ResultSet rsCekId = psCekId.executeQuery();
        
        int nextId = 1;
        if (rsCekId.next()) {
            nextId = rsCekId.getInt("max_id") + 1;
        }
        rsCekId.close();
        psCekId.close();
        
        // Format angka urutan menjadi 5 digit (contoh: 00003)
        String nomorUrut = String.format("%04d", nextId);

        // Menentukan prefix/awalan berdasarkan hasil klasifikasi database
        if (jenisKlasifikasi.equalsIgnoreCase("emergency")) {
            kodeLaporanOtomatis = "EMR-" + nomorUrut;
        } else {
            kodeLaporanOtomatis = "NEM-" + nomorUrut;
        }
        // =======================================================================

        
        // 3. JALANKAN QUERY INSERT
        String sqlInsert = "INSERT INTO laporan_penanganan "
                   + "(kode_laporan, id_form_pengaduan, id_instansi, id_operator, deskripsi_penanganan, alamat, tanggal_laporan, foto_media) "
                   + "VALUES (?, (SELECT id_form_pengaduan FROM form_pengaduan WHERE kode_pengaduan = ?), ?, ?, ?, ?, ?, ?)";
        
        java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
        
        psInsert.setString(1, kodeLaporanOtomatis); 
        psInsert.setString(2, kodePengaduan);       
        psInsert.setInt(3, idInstansiLogedIn);      
        psInsert.setInt(4, idOperatorLogedIn);      
        psInsert.setString(5, deskripsiPenanganan); 
        psInsert.setString(6, alamat);              
        psInsert.setString(7, tglLaporan);          
        
        java.io.FileInputStream fis = new java.io.FileInputStream(fileGambar);
        psInsert.setBinaryStream(8, fis, (int) fileGambar.length());
        
        int rows = psInsert.executeUpdate();
        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "Laporan berhasil dikirim!\nKode Laporan Baru: " + kodeLaporanOtomatis);
            area_detail.setText("");
        }
        
        psInsert.close();
        fis.close();
        conn.close();
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }

    
   
        
       
    

    

   

    }//GEN-LAST:event_btn_kirimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new isilaporanhasilpenangananInstansi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_alamat;
    private javax.swing.JTextArea area_detail;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JTextField field_kd;
    private javax.swing.JTextField field_tgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
